### ISSUE TITLE
demo not working?

### ISSUE THREAD

**Issue by suriyaJaay** [laarniastrid/hauntEm#1]
hi, i've found demo for this app is not working fine in following 
http://trollem.herokuapp.com

also am try to run this app in my local machine.. it throws fallowing error

Error: secret option required for sessions
    at session (F:\trollEm-master\node_modules\express-session\index.js:199:12)
    at Layer.handle [as handle_request] (F:\trollEm-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (F:\trollEm-master\node_modules\express\lib\router\index.js:312:13)
    at F:\trollEm-master\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (F:\trollEm-master\node_modules\express\lib\router\index.js:330:12)
    at next (F:\trollEm-master\node_modules\express\lib\router\index.js:271:10)
    at serveStatic (F:\trollEm-master\node_modules\express\node_modules\serve-static\index.js:75:16)
    at Layer.handle [as handle_request] (F:\trollEm-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (F:\trollEm-master\node_modules\express\lib\router\index.js:312:13)
    at F:\trollEm-master\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (F:\trollEm-master\node_modules\express\lib\router\index.js:330:12)
    at next (F:\trollEm-master\node_modules\express\lib\router\index.js:271:10)
    at F:\trollEm-master\node_modules\body-parser\lib\read.js:129:5
    at invokeCallback (F:\trollEm-master\node_modules\body-parser\node_modules\raw-body\index.js:262:16)
    at done (F:\trollEm-master\node_modules\body-parser\node_modules\raw-body\index.js:251:7)
    at IncomingMessage.onEnd (F:\trollEm-master\node_modules\body-parser\node_modules\raw-body\index.js:307:7)

**Comment by laarniastrid** [comment]
Hey thanks for the message.  I haven't worked on this demo in quite a while, but have redeployed the site so hopefully the live version will work for you now.  It's pretty buggy since it was a quick student project, sorry.

For the error you're receiving, do you have a keys.js file for all the auth keys/passwords?

**Comment by suriyaJaay** [comment]
nope.. i dont have key file

**Comment by laarniastrid** [comment]
This demo does require a keys.js file unless you're using environment variables like I did with Heroku.  Try getting that added and switched out on your local code first and see if that helps.  If you use a keys.js file, be sure to add that to your .gitignore file so it's not uploaded to github.
